#!/usr/bin/env python3
"""Build, measure and trivy-scan the Java base image matrix defined in matrix.py."""
import argparse
import concurrent.futures as cf
import csv
import datetime as dt
import json
import os
import pathlib
import queue
import re
import shlex
import subprocess
import time
import urllib.request

from matrix import APT_REPOS, OS, RPM_REPOS, base_cells, cells

ROOT = pathlib.Path(__file__).resolve().parent
DOCKER = shlex.split(os.environ.get("JBI_DOCKER", "docker"))
TRIVY = shlex.split(os.environ.get("JBI_TRIVY", "trivy"))
KEYS = ROOT / "build" / "keys"
TRIVY_CACHE = ROOT / "build" / "trivy-cache"  # one dir per scan worker: trivy locks its cache exclusively
DOCKERFILES = ROOT / "dockerfiles"
SEVERITIES = ["critical", "high", "medium", "low", "unknown"]

UPGRADE = {
    "apk": "apk upgrade --no-cache",
    "apt": "apt-get update && apt-get -y dist-upgrade && apt-get clean && rm -rf /var/lib/apt/lists/*",
    # Amazon Linux 2023 images lock to a repository snapshot; without --releasever=latest nothing is upgraded
    "dnf": "if grep -q '^ID=\"amzn\"' /etc/os-release; then dnf -y --releasever=latest upgrade; else dnf -y upgrade; fi && dnf clean all",
    "microdnf": "microdnf -y upgrade && microdnf clean all",
    "tdnf": "tdnf -y upgrade && tdnf clean all",
}
# Official images do not declare their package manager, so probe for it.
AUTO_UPGRADE = "set -e; " + "; ".join(
    f"{'if' if i == 0 else 'elif'} command -v {'apt-get' if pm == 'apt' else pm} >/dev/null; then {cmd}"
    for i, (pm, cmd) in enumerate(UPGRADE.items())) + "; else echo 'no known package manager' >&2; exit 1; fi"

PROBE = r"""cat /etc/os-release; echo '===JAVA==='
L=""; [ -e /lib/ld-musl-x86_64.so.1 ] && L=musl
if [ -e /lib64/ld-linux-x86-64.so.2 ] || [ -e /lib/x86_64-linux-gnu/libc.so.6 ]; then L="${L:+$L+}glibc"; fi
echo "LIBC=${L:-unknown}"
[ -e /lib/ld-musl-x86_64.so.1 ] && echo "MUSL_VERSION=$(/lib/ld-musl-x86_64.so.1 2>&1 | sed -n 's/^Version //p')"
for LD in /lib64/ld-linux-x86-64.so.2 /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2; do [ -e "$LD" ] && { echo "GLIBC_VERSION=$($LD --version 2>&1 | sed -n '1s/.*version \([0-9.]*[0-9]\).*$/\1/p')"; break; }; done
J=$(command -v java 2>/dev/null || true)
[ -z "$J" ] && [ -n "$JAVA_HOME" ] && J="$JAVA_HOME/bin/java"
[ -x "$J" ] || J=$(find / -type f -name java -path '*/bin/java' 2>/dev/null | head -1)
echo "JAVA_BIN=$J"
if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then JH=$JAVA_HOME; else JH=$(dirname "$(dirname "$(readlink -f "$J")")"); case "$JH" in */jre) JH=$(dirname "$JH");; esac; fi
JH=$(readlink -f "$JH"); echo "JAVA_HOME_DIR=$JH"; echo "JAVA_HOME_KB=$(du -sk "$JH" 2>/dev/null | cut -f1)"
"$J" -XshowSettings:properties -version 2>&1"""


def log(msg):
    print(f"[{dt.datetime.now():%H:%M:%S}] {msg}", flush=True)


def run(cmd, timeout=None):
    return subprocess.run(cmd, text=True, capture_output=True, timeout=timeout)


def docker(*args, **kw):
    return run(DOCKER + list(args), **kw)


def parallel(fn, items, workers):
    with cf.ThreadPoolExecutor(max_workers=workers) as ex:
        return list(ex.map(fn, items))


# ---------- dockerfiles ----------

def dockerfile(cell, variant, orig_user):
    lines = [f"# generated by jbi.py -- {cell.name}:{variant}", f"FROM {cell.base_image}"]
    if cell.method == "official":
        if variant == "updated":
            lines += ["USER root", f"RUN {AUTO_UPGRADE}"] + ([f"USER {orig_user}"] if orig_user else [])
        return "\n".join(lines) + "\n"
    lines.append(f"RUN {UPGRADE[cell.pm]}")
    if cell.pm == "apt":
        steps = []
        if cell.repo:
            _, line, conf = APT_REPOS[cell.repo]
            lines.append(f"COPY build/keys/{cell.repo}.asc /etc/apt/keyrings/{cell.repo}.asc")
            if conf:
                steps.append(f"printf '{conf}\\n' > /etc/apt/apt.conf.d/99-{cell.repo}")
            steps += ["apt-get update", "apt-get install -y --no-install-recommends ca-certificates",
                      f'echo "deb [signed-by=/etc/apt/keyrings/{cell.repo}.asc] {line.format(codename=OS[cell.os][2])}"'
                      f" > /etc/apt/sources.list.d/{cell.repo}.list"]
        steps += ["apt-get update", f"apt-get install -y --no-install-recommends {cell.pkg}",
                  "apt-get clean && rm -rf /var/lib/apt/lists/*"]
    else:
        steps = []
        if cell.repo:
            name, baseurl, gpgkey = RPM_REPOS[cell.repo]
            steps.append(f"printf '[{cell.repo}]\\nname={name}\\nbaseurl={baseurl}\\nenabled=1\\ngpgcheck=1\\ngpgkey={gpgkey}\\n'"
                         f" > /etc/yum.repos.d/{cell.repo}.repo")
        steps += [f"{cell.pm} -y --setopt=install_weak_deps=0 --nodocs install {cell.pkg}", f"{cell.pm} clean all"]
    lines.append("RUN " + " \\\n && ".join(steps))
    return "\n".join(lines) + "\n"


def fetch_keys():
    KEYS.mkdir(parents=True, exist_ok=True)
    for name, (url, _, _) in APT_REPOS.items():
        dest = KEYS / f"{name}.asc"
        if not dest.exists():
            data = urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": "curl/8"}), timeout=60).read()
            if not data.startswith(b"-----BEGIN PGP"):
                raise SystemExit(f"{url}: expected an ASCII-armored key")
            dest.write_bytes(data)


def image_user(image):
    r = docker("image", "inspect", "--format", "{{.Config.User}}", image)
    return r.stdout.strip() if r.returncode == 0 else ""


def pull(image, retries=12, wait=600):
    for attempt in range(retries):
        r = docker("pull", "--platform", "linux/amd64", "-q", image, timeout=1800)
        if r.returncode == 0:
            return True
        if "toomanyrequests" in r.stderr or "rate limit" in r.stderr.lower():
            log(f"pull {image}: rate limited, waiting {wait}s ({attempt + 1}/{retries})")
            time.sleep(wait)
            continue
        log(f"pull {image} FAILED: {(r.stderr.strip().splitlines() or [r.stdout])[-1]}")
        return False
    return False


# ---------- per-image work ----------

class Job:
    def __init__(self, cell, variant, rdir):
        self.cell, self.variant, self.rdir = cell, variant, rdir
        self.tag = cell.tag(variant)
        self.key = f"{cell.name}-{variant}"
        self.path = rdir / "images" / f"{self.key}.json"

    def load(self):
        return json.loads(self.path.read_text()) if self.path.exists() else {}

    def save(self, **fields):
        self.path.parent.mkdir(parents=True, exist_ok=True)
        d = self.load()
        d.update(fields)
        self.path.write_text(json.dumps(d, indent=1, sort_keys=True))
        return d


def build(job):
    c = job.cell
    df = DOCKERFILES / c.name / f"{job.variant}.Dockerfile"
    logf = job.rdir / "logs" / f"{job.key}.build.log"
    logf.parent.mkdir(parents=True, exist_ok=True)
    t0 = time.time()
    r = docker("build", "--no-cache", "--platform", "linux/amd64", "-f", str(df), "-t", job.tag, str(ROOT), timeout=3600)
    logf.write_text(r.stdout + r.stderr)
    ok = r.returncode == 0
    job.save(vendor=c.vendor, java=c.java, os=c.os, flavor=c.flavor, variant=job.variant, method=c.method,
             source=c.image or (f"{c.repo}:{c.pkg}" if c.repo else c.pkg), note=c.note, base_image=c.base_image,
             tag=job.tag, build_ok=ok, build_seconds=round(time.time() - t0),
             built_at=dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
             build_error="" if ok else (r.stderr.strip().splitlines() or ["?"])[-1][:300])
    log(f"build {job.tag}: {'ok' if ok else 'FAILED'} ({round(time.time() - t0)}s)")
    return ok


_STORE = {}


def containerd_store():
    if "containerd" not in _STORE:
        _STORE["containerd"] = "io.containerd.snapshotter" in docker("info", "--format", "{{json .DriverStatus}}").stdout
    return _STORE["containerd"]


def measure(job):
    if not job.load().get("build_ok"):
        return False
    r = docker("history", "--human=false", "--format", "{{.Size}}", job.tag)
    size = sum(int(x) for x in r.stdout.split()) if r.returncode == 0 else None
    r = docker("image", "inspect", "--format", "{{.Size}}", job.tag)
    # the containerd image store reports compressed + uncompressed as .Size; the classic store reports uncompressed only
    compressed = int(r.stdout.strip()) - size if r.returncode == 0 and size is not None and containerd_store() else None
    r = docker("image", "inspect", "--format", "{{index .RepoDigests 0}}", job.cell.base_image)
    digest = r.stdout.strip() if r.returncode == 0 else ""
    r = docker("run", "--rm", "--platform", "linux/amd64", "--user", "0", "--entrypoint", "/bin/sh", job.tag, "-c", PROBE, timeout=300)
    out = r.stdout + r.stderr
    osrel, _, javaout = out.partition("===JAVA===")
    osr = dict(re.findall(r'^(\w+)="?([^"\n]*)"?$', osrel, re.M))
    kv = dict(re.findall(r"^(LIBC|MUSL_VERSION|GLIBC_VERSION|JAVA_BIN|JAVA_HOME_DIR|JAVA_HOME_KB)=(.*)$", javaout, re.M))
    props = {m.group(1): m.group(2).strip() for m in re.finditer(r"^\s+([\w.]+) = (.*)$", javaout, re.M)}
    ver = re.search(r'(?:openjdk|java) version "([^"]+)"', javaout)
    job.save(size_bytes=size, compressed_bytes=compressed, base_digest=digest,
             libc=kv.get("LIBC", ""), libc_version=" / ".join(v for v in (kv.get("MUSL_VERSION"), kv.get("GLIBC_VERSION")) if v),
             os_id=osr.get("ID", ""), os_version_id=osr.get("VERSION_ID", ""), os_pretty_name=osr.get("PRETTY_NAME", ""),
             java_bin=kv.get("JAVA_BIN", ""), java_home=kv.get("JAVA_HOME_DIR", ""),
             java_home_bytes=int(kv["JAVA_HOME_KB"]) * 1024 if kv.get("JAVA_HOME_KB", "").isdigit() else None,
             java_version=ver.group(1) if ver else "", java_runtime_version=props.get("java.runtime.version", ""),
             java_vendor=props.get("java.vendor", ""), java_vendor_version=props.get("java.vendor.version", ""),
             java_vm_name=props.get("java.vm.name", ""),
             probe_ok=bool(props) or (job.cell.java == 0 and bool(osr)), probe_tail="" if props else javaout[-500:])
    log(f"measure {job.tag}: {osr.get('PRETTY_NAME', '?')} / {props.get('java.runtime.version', '-')} / {size}")
    return True


def trivy(cache, *args, **kw):
    return run(TRIVY + ["--cache-dir", str(cache)] + list(args), **kw)


def trivy_caches(n):
    caches = [TRIVY_CACHE / str(i) for i in range(n)]

    def prep(c):
        c.mkdir(parents=True, exist_ok=True)
        for flag in ("--download-db-only", "--download-java-db-only"):
            r = trivy(c, "image", flag, timeout=1800)
            if r.returncode:
                raise SystemExit(f"trivy {flag} into {c} failed: {r.stderr[-500:]}")
    parallel(prep, caches, n)
    q = queue.Queue()
    for c in caches:
        q.put(c)
    return q


def trivy_meta():
    r = trivy(TRIVY_CACHE / "0", "version", "--format", "json")
    j = json.loads(r.stdout) if r.returncode == 0 else {}
    return {"trivy_version": j.get("Version", ""), "trivy_db_updated": (j.get("VulnerabilityDB") or {}).get("UpdatedAt", "")}


def scan(job, meta, caches):
    if not job.load().get("build_ok"):
        return False
    out = job.rdir / "trivy" / f"{job.key}.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    cache = caches.get()
    try:
        r = trivy(cache, "image", "--quiet", "--skip-db-update", "--skip-java-db-update", "--scanners", "vuln",
                  "--format", "json", "--output", str(out), job.tag, timeout=1800)
    finally:
        caches.put(cache)
    if r.returncode != 0:
        job.save(scan_ok=False, scan_error=r.stderr.strip()[-300:])
        log(f"scan {job.tag}: FAILED")
        return False
    j = json.loads(out.read_text())
    counts, fixable = dict.fromkeys(SEVERITIES, 0), dict.fromkeys(SEVERITIES, 0)
    for res in j.get("Results") or []:
        for v in res.get("Vulnerabilities") or []:
            s = v.get("Severity", "UNKNOWN").lower()
            counts[s] = counts.get(s, 0) + 1
            if v.get("FixedVersion"):
                fixable[s] = fixable.get(s, 0) + 1
    md = j.get("Metadata", {}).get("OS", {}) or {}
    job.save(scan_ok=True, vuln=counts, fixable=fixable, trivy_os=f"{md.get('Family', '')} {md.get('Name', '')}".strip(),
             trivy_eosl=bool(md.get("EOSL")), **meta)
    log(f"scan {job.tag}: C{counts['critical']} H{counts['high']} M{counts['medium']} L{counts['low']}")
    return True


# ---------- reporting ----------

COLUMNS = ["vendor", "java", "os", "flavor", "variant", "status", "method", "source", "size_bytes", "size_mb",
           "compressed_bytes", "compressed_mb", "java_home_mb", "os_id", "os_version_id", "os_pretty_name", "libc",
           "libc_version", "java_version", "java_runtime_version", "java_vendor", "java_vm_name", "trivy_os", "trivy_eosl",
           "vuln_critical", "vuln_high", "vuln_medium", "vuln_low", "vuln_unknown", "vuln_total",
           "fixable_critical", "fixable_high", "fixable_medium", "fixable_low", "fixable_unknown", "fixable_total",
           "base_image", "base_digest", "built_at", "build_seconds", "trivy_version", "trivy_db_updated", "note"]


def row_of(d):
    r = {k: d.get(k, "") for k in COLUMNS}
    if d.get("java_home_bytes"):
        r["java_home_mb"] = round(d["java_home_bytes"] / 1e6, 1)
    for k in ("size", "compressed"):
        if d.get(f"{k}_bytes") not in (None, ""):
            r[f"{k}_mb"] = round(d[f"{k}_bytes"] / 1e6, 1)
    for kind in ("vuln", "fixable"):
        sub = d.get(kind) or {}
        if sub:
            for s in SEVERITIES:
                r[f"{kind}_{s}"] = sub.get(s, 0)
            r[f"{kind}_total"] = sum(sub.values())
    if d.get("status"):
        r["status"] = d["status"]
    elif not d.get("build_ok"):
        r["status"], r["note"] = "build-failed", d.get("build_error", "")
    elif not d.get("scan_ok"):
        r["status"] = "scan-failed"
    elif not d.get("probe_ok"):
        m = re.search(r"SIGSEGV|Error occurred[^\n]*|Problematic frame:\s*#\s*[^\n]*", d.get("probe_tail", ""))
        r["status"], r["note"] = "probe-failed", "JVM did not start: " + (m.group(0).strip() if m else "see probe_tail")
    else:
        r["status"] = "ok"
    return r


def sev(r):
    return " | ".join(f"{r[f'vuln_{s}']} ({r[f'fixable_{s}']})" for s in SEVERITIES[:4])


def report(rdir, selected):
    rows = []
    for cell in selected:
        if cell.method == "none":
            rows.append(row_of(dict(vendor=cell.vendor, java=cell.java, os=cell.os, flavor=cell.flavor, variant="",
                                    status="not-available", method="none", note=cell.note)))
            continue
        for variant in cell.variants:
            d = Job(cell, variant, rdir).load() or dict(vendor=cell.vendor, java=cell.java, os=cell.os, flavor=cell.flavor,
                                                        variant=variant, method=cell.method, status="not-built", note=cell.note)
            rows.append(row_of(d))
    with open(rdir / "summary.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=COLUMNS)
        w.writeheader()
        w.writerows(rows)
    meta = trivy_meta()
    ok = [r for r in rows if r["status"] == "ok"]
    md = [f"# Java image matrix -- run {rdir.name}", "",
          f"Generated {dt.datetime.now(dt.timezone.utc):%Y-%m-%d %H:%M} UTC with trivy {meta['trivy_version']}, "
          f"DB {meta['trivy_db_updated']}. Vulnerability columns count trivy findings over OS packages and bundled "
          "Java libraries, all severities, fixed and unfixed; the number in parentheses is the fixable subset. "
          "Size is the uncompressed image on disk, compressed is the registry transfer size. "
          "`base` is the vendor image as published, `updated` has the OS packages upgraded "
          "(for repo installs the OS is upgraded before Java is installed).", "",
          "| Vendor | Java | OS | Flavor | Variant | Method | Size MB | Compressed MB | Java home MB | OS version | libc | Java version | Critical | High | Medium | Low |",
          "|---|---|---|---|---|---|---:|---:|---:|---|---|---|---:|---:|---:|---:|"]
    md += [f"| {r['vendor']} | {r['java']} | {r['os']} | {r['flavor']} | {r['variant']} | {r['method']} | {r['size_mb']} | "
           f"{r['compressed_mb']} | {r['java_home_mb']} | {r['os_pretty_name']} | {r['libc']} {r['libc_version']} | "
           f"{r['java_runtime_version']} | {sev(r)} |" for r in ok]
    other = [r for r in rows if r["status"] != "ok"]
    if other:
        md += ["", "## Not available or not built", "", "| Vendor | Java | OS | Flavor | Variant | Status | Reason |", "|---|---|---|---|---|---|---|"]
        md += [f"| {r['vendor']} | {r['java']} | {r['os']} | {r['flavor']} | {r['variant']} | {r['status']} | {r['note']} |" for r in other]
    (rdir / "report.md").write_text("\n".join(md) + "\n")
    log(f"report: {len(ok)} ok, {len(other)} other rows -> {rdir / 'summary.csv'}")


def baseos(rdir, workers):
    jobs = [Job(c, v, rdir) for c in base_cells() for v in c.variants]
    parallel(pull, {j.cell.image for j in jobs}, 3)
    for j in jobs:
        d = DOCKERFILES / j.cell.name
        d.mkdir(parents=True, exist_ok=True)
        (d / f"{j.variant}.Dockerfile").write_text(dockerfile(j.cell, j.variant, image_user(j.cell.image)))
    parallel(build, jobs, workers)
    parallel(measure, jobs, workers)
    caches = trivy_caches(workers)
    meta = trivy_meta()
    parallel(lambda j: scan(j, meta, caches), jobs, workers)
    rows = [row_of(j.load()) for j in jobs]
    cols = ["os", "variant", "status", "base_image", "size_mb", "compressed_mb", "os_pretty_name", "libc", "libc_version",
            "trivy_os", "vuln_critical", "vuln_high", "vuln_medium", "vuln_low", "fixable_critical", "fixable_high",
            "fixable_medium", "fixable_low", "base_digest", "built_at"]
    with open(rdir / "base-os.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)
    md = [f"# Base OS images -- run {rdir.name}", "", "| OS | Variant | Size MB | Compressed MB | OS version | libc | Critical | High | Medium | Low |",
          "|---|---|---:|---:|---|---|---:|---:|---:|---:|"]
    md += [f"| {r['os']} | {r['variant']} | {r['size_mb']} | {r['compressed_mb']} | {r['os_pretty_name']} | {r['libc']} {r['libc_version']} | {sev(r)} |"
           for r in rows if r["status"] == "ok"]
    (rdir / "base-os.md").write_text("\n".join(md) + "\n")
    log(f"baseos: {sum(r['status'] == 'ok' for r in rows)}/{len(rows)} ok -> {rdir / 'base-os.csv'}")


MUSL_OS = {"alpine"}
CAVEATS = {
    ("zulu", "alpine"): "Azul pins Alpine 3.23 in the Docker Official Image; community builds have no published end-of-updates dates",
    ("zulu", "debian"): "community builds have no published end-of-updates dates",
    ("zulu", "ubuntu"): "apt repo needs the bz2 index (CDN serves a stale Packages.gz); no published end-of-updates dates",
    ("temurin", "alpine"): "official image lags the quarterly release by 2-5 weeks",
    ("temurin", "ubuntu"): "official image lags the quarterly release by 2-5 weeks",
    ("redhat", "ubi9-minimal"): "builder images bundle Maven and S2I; UBI 9 findings have no fix without a RHEL subscription",
    ("oracle", "oraclelinux"): "GPL OpenJDK images are frozen at the last update before the next feature release",
    ("corretto", "alpine"): "no Corretto JRE on Alpine; OS package updates are the user's job",
    ("corretto", "al2023"): "published image is a repository snapshot; upgrade with --releasever=latest",
}
REC_COLUMNS = ["java", "flavor", "rank", "kind", "vendor", "os", "variant", "method", "source", "size_mb", "compressed_mb",
               "os_pretty_name", "libc", "java_runtime_version", "vuln_critical", "vuln_high", "vuln_medium", "vuln_low",
               "candidates", "caveat"]


def recommend(rdir, top=5):
    rows = [r for r in csv.DictReader(open(rdir / "summary.csv")) if r["status"] == "ok"]
    out, md = [], [f"# Recommended images -- run {rdir.name}", "",
                   "Rule: no critical or high findings; then fewest medium+low findings; then smallest uncompressed size. "
                   "`glibc` rows are the best candidate outside Alpine (musl) for workloads that need glibc. "
                   "Rank 2+ rows are the runners-up under the same rule.", "",
                   "| Java | Flavor | Kind | Vendor | OS | Variant | Method | Size MB | Compressed MB | OS version | Java version | Medium | Low | Caveat |",
                   "|---|---|---|---|---|---|---|---:|---:|---|---|---:|---:|---|"]
    for java in sorted({int(r["java"]) for r in rows}):
        for flavor in ("jdk", "jre"):
            group = [r for r in rows if int(r["java"]) == java and r["flavor"] == flavor]
            ok = sorted((r for r in group if r["vuln_critical"] == "0" and r["vuln_high"] == "0"),
                        key=lambda r: (int(r["vuln_medium"]) + int(r["vuln_low"]), float(r["size_mb"])))
            picks = [("recommended" if i == 0 else "runner-up", i + 1, r) for i, r in enumerate(ok[:top])]
            glibc = next((r for r in ok if r["os"] not in MUSL_OS), None)
            if glibc and glibc is not ok[0]:
                picks.append(("glibc", ok.index(glibc) + 1, glibc))
            for kind, rank, r in picks:
                rec = {k: r.get(k, "") for k in REC_COLUMNS}
                rec.update(java=java, flavor=flavor, rank=rank, kind=kind, candidates=f"{len(ok)}/{len(group)}",
                           caveat=CAVEATS.get((r["vendor"], r["os"]), ""))
                out.append(rec)
                if kind != "runner-up":
                    md.append(f"| {java} | {flavor} | {kind} | {r['vendor']} | {r['os']} | {r['variant']} | {r['method']} | {r['size_mb']} | "
                              f"{r['compressed_mb']} | {r['os_pretty_name']} | {r['java_runtime_version']} | {r['vuln_medium']} | {r['vuln_low']} | {rec['caveat']} |")
            if not ok:
                md.append(f"| {java} | {flavor} | none | | | | | | | | | | | no image without critical/high findings |")
    md += ["", "## Runners-up", "", "| Java | Flavor | Rank | Vendor | OS | Variant | Size MB | Medium | Low | Java version |", "|---|---|---|---|---|---|---:|---:|---:|---|"]
    md += [f"| {r['java']} | {r['flavor']} | {r['rank']} | {r['vendor']} | {r['os']} | {r['variant']} | {r['size_mb']} | "
           f"{r['vuln_medium']} | {r['vuln_low']} | {r['java_runtime_version']} |" for r in out if r["kind"] == "runner-up"]
    with open(rdir / "recommendations.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=REC_COLUMNS)
        w.writeheader()
        w.writerows(out)
    (rdir / "recommendations.md").write_text("\n".join(md) + "\n")
    log(f"recommend: {sum(1 for r in out if r['kind'] == 'recommended')} pairs -> {rdir / 'recommendations.csv'}")


# ---------- cli ----------

def select(args):
    return [c for c in cells()
            if (not args.vendor or c.vendor in args.vendor) and (not args.java or c.java in args.java)
            and (not args.os or c.os in args.os) and (not args.flavor or c.flavor in args.flavor)
            and (not args.method or c.method in args.method)]


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("stages", nargs="+", choices=["matrix", "pull", "generate", "build", "measure", "scan", "report", "recommend", "baseos", "all"])
    p.add_argument("--run-id", default=dt.date.today().isoformat(), help="results/<run-id> (default: today)")
    p.add_argument("-j", "--workers", type=int, default=4)
    p.add_argument("--vendor", nargs="*")
    p.add_argument("--java", nargs="*", type=int)
    p.add_argument("--os", nargs="*")
    p.add_argument("--flavor", nargs="*")
    p.add_argument("--variant", nargs="*", choices=["base", "updated"])
    p.add_argument("--method", nargs="*", choices=["official", "repo", "none"])
    p.add_argument("--retry-failed", action="store_true", help="build: only images whose previous build failed")
    args = p.parse_args()
    stages = ["pull", "generate", "build", "measure", "scan", "report", "recommend", "baseos"] if "all" in args.stages else args.stages
    rdir = ROOT / "results" / args.run_id
    selected = select(args)
    buildable = [c for c in selected if c.method != "none"]
    jobs = [Job(c, v, rdir) for c in buildable for v in c.variants if not args.variant or v in args.variant]

    if "matrix" in stages:
        for c in selected:
            print(f"{c.name:34} {c.method:9} {c.image or c.pkg or c.note}")
        print(f"{len(buildable)} buildable cells ({len(jobs)} images), {len(selected) - len(buildable)} not available")
    if "pull" in stages:
        images = sorted({c.base_image for c in buildable})
        log(f"pulling {len(images)} base images")
        parallel(pull, images, min(args.workers, 3))
    if "generate" in stages:
        fetch_keys()
        for j in jobs:
            d = DOCKERFILES / j.cell.name
            d.mkdir(parents=True, exist_ok=True)
            (d / f"{j.variant}.Dockerfile").write_text(dockerfile(j.cell, j.variant, image_user(j.cell.image) if j.cell.method == "official" else ""))
        log(f"generated {len(jobs)} dockerfiles")
    if "build" in stages:
        todo = [j for j in jobs if j.path.exists() and not j.load().get("build_ok")] if args.retry_failed else jobs
        log(f"building {len(todo)} images with {args.workers} workers")
        parallel(build, todo, args.workers)
    if "measure" in stages:
        parallel(measure, jobs, args.workers)
    if "scan" in stages:
        caches = trivy_caches(args.workers)
        meta = trivy_meta()
        parallel(lambda j: scan(j, meta, caches), jobs, args.workers)
    if "report" in stages:
        report(rdir, selected)
    if "recommend" in stages:
        recommend(rdir)
    if "baseos" in stages:
        baseos(rdir, args.workers)


if __name__ == "__main__":
    main()
