# generated by jbi.py -- redhat-25-ubi9-jre:updated
FROM registry.access.redhat.com/ubi9/ubi:latest
RUN if grep -q '^ID="amzn"' /etc/os-release; then dnf -y --releasever=latest upgrade; else dnf -y upgrade; fi && dnf clean all
RUN dnf -y --setopt=install_weak_deps=0 --nodocs install java-25-openjdk-headless \
 && dnf clean all
