# generated by jbi.py -- corretto-17-debian-jdk:updated
FROM debian:trixie-slim
RUN apt-get update && apt-get -y dist-upgrade && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY build/keys/corretto.asc /etc/apt/keyrings/corretto.asc
RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates \
 && echo "deb [signed-by=/etc/apt/keyrings/corretto.asc] https://apt.corretto.aws stable main" > /etc/apt/sources.list.d/corretto.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends java-17-amazon-corretto-jdk \
 && apt-get clean && rm -rf /var/lib/apt/lists/*
