# generated by jbi.py -- redhat-25-ubi10-jdk:updated
FROM registry.access.redhat.com/ubi10/ubi:latest
RUN if grep -q '^ID="amzn"' /etc/os-release; then dnf -y --releasever=latest upgrade; else dnf -y upgrade; fi && dnf clean all
RUN dnf -y --setopt=install_weak_deps=0 --nodocs install java-25-openjdk-devel \
 && dnf clean all
