# generated by jbi.py -- base-ubi9-minimal:updated
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
USER root
RUN set -e; if command -v apk >/dev/null; then apk upgrade --no-cache; elif command -v apt-get >/dev/null; then apt-get update && apt-get -y dist-upgrade && apt-get clean && rm -rf /var/lib/apt/lists/*; elif command -v dnf >/dev/null; then if grep -q '^ID="amzn"' /etc/os-release; then dnf -y --releasever=latest upgrade; else dnf -y upgrade; fi && dnf clean all; elif command -v microdnf >/dev/null; then microdnf -y upgrade && microdnf clean all; elif command -v tdnf >/dev/null; then tdnf -y upgrade && tdnf clean all; else echo 'no known package manager' >&2; exit 1; fi
