# generated by jbi.py -- zulu-21-ubuntu-jdk:updated
FROM ubuntu:26.04
RUN apt-get update && apt-get -y dist-upgrade && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY build/keys/zulu.asc /etc/apt/keyrings/zulu.asc
RUN printf '#clear Acquire::CompressionTypes::Order;\nAcquire::CompressionTypes::Order { "bz2"; };\n' > /etc/apt/apt.conf.d/99-zulu \
 && apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates \
 && echo "deb [signed-by=/etc/apt/keyrings/zulu.asc] https://repos.azul.com/zulu/deb stable main" > /etc/apt/sources.list.d/zulu.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends zulu21-jdk \
 && apt-get clean && rm -rf /var/lib/apt/lists/*
