# generated by jbi.py -- temurin-21-debian-jdk:updated
FROM debian:trixie-slim
RUN apt-get update && apt-get -y dist-upgrade && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY build/keys/adoptium.asc /etc/apt/keyrings/adoptium.asc
RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates \
 && echo "deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb trixie main" > /etc/apt/sources.list.d/adoptium.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends temurin-21-jdk \
 && apt-get clean && rm -rf /var/lib/apt/lists/*
