# generated by jbi.py -- redhat-17-ubi9-jdk:updated
FROM registry.access.redhat.com/ubi9/ubi:latest
RUN if grep -q '^ID="amzn"' /etc/os-release; then dnf -y --releasever=latest upgrade; else dnf -y upgrade; fi && dnf clean all
RUN dnf -y --setopt=install_weak_deps=0 --nodocs install java-17-openjdk-devel \
 && dnf clean all
